// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

void* winrt_make_HL2MarkerTracking_MarkerTracker()
{
    return winrt::detach_abi(winrt::make<winrt::HL2MarkerTracking::factory_implementation::MarkerTracker>());
}
WINRT_EXPORT namespace winrt::HL2MarkerTracking
{
    MarkerTracker::MarkerTracker(array_view<float const> geometry, array_view<float const> extrinsicsCorrection, bool verbose) :
        MarkerTracker(make<HL2MarkerTracking::implementation::MarkerTracker>(geometry, extrinsicsCorrection, verbose))
    {
    }
}
