// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_HL2MarkerTracking_1_H
#define WINRT_HL2MarkerTracking_1_H
#include "winrt/impl/HL2MarkerTracking.0.h"
WINRT_EXPORT namespace winrt::HL2MarkerTracking
{
    struct __declspec(empty_bases) IMarkerTracker :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMarkerTracker>
    {
        IMarkerTracker(std::nullptr_t = nullptr) noexcept {}
        IMarkerTracker(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMarkerTrackerFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMarkerTrackerFactory>
    {
        IMarkerTrackerFactory(std::nullptr_t = nullptr) noexcept {}
        IMarkerTrackerFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
